name: ntf
channels:
  - conda-forge
  - defaults
dependencies:
  - dash==1.4.1
  - dash-core-components==1.3.1
  - dash-html-components==1.0.1
  - geopandas
  - matplotlib
  - numpy
  - pandas
  - pip=19.3.1
  - plotly=4.2.1
  - pylint
  - pytest
  - python=3.7.3